name: "HyLores"
version: 0.2.7b1
description: "Hykilpikonna's lore items"
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.lores.HyLores
depend: [HyEssentials]
commands:
    hyl:
        description: The command.
        usage: /<command>
        aliases: [hylores,hylore]