name: "HyLores"
version: 0.1.2_b5
description: "Hykilpikonna's lore items"
author: Hykilpikonna
main: cc.moecraft.hykilpikonna.lores.HyLores
depend: [HyEssentials]
commands:
    hyl:
        description: The command.